
name: test

inputs:
  image:
    description: 'image'
    required: true
    type: string

runs:
  using: 'composite'
  steps:

    - name: Run test
      run: |
        echo "called"
