# .github/workflows/b.yml
name: Main Workflow

on:
  workflow_dispatch:
    inputs:
      system:
        description: 'system'
        required: true
        type: choices
        options:
          - windows
          - linux
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Call Workflow
        if: ${{ inputs.system == 'windows' }}
        uses: ./.github/workflows/actions/b
      
      - name: echo
        shell: bash
        run: |
          echo done