# .github/workflows/b.yml
name: Main Workflow

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Call Workflow
        uses: ./.github/workflows/a.yml
        with:
          image: mycoolimage
