# .github/workflows/b.yml
name: Main Workflow

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Call Workflow
        uses: ./.github/workflows/actions/b
        with:
          image: mycoolimage
