name: Download

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs: 
  az-auth:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: 'Run Azure CLI commands'
        shell: powershell
        run: |
            $blobArray = "jdk-11.0.23-windows-x64.zip,windows-testimage-11.0.23-windows-x64.zip" -split ','
            foreach ($blob in $blobArray) {
                az storage blob download `
                --account-name "${{ secrets.storage_acct }}" `
                --container-name "${{ secrets.container }}" `
                --name "$blob" `
                --file ".\$blob" `
                --auth-mode login
            }