name: Az Download
on:
  workflow_call:
      
jobs: 
  download-blob:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'Run Azure CLI commands'
        run: |
            az storage blob download --account-name joedocumentstorage --container-name newcontainer --name README.txt --file ./README.txt --auth-mode login