name: Run Azure Login with OpenID Connect
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
      
jobs: 
  build:
    uses: ./.github/workflows/az_auth.yml
    secrets: inherit
  download:
    uses: ./.github/workflows/az_download.yml
    secrets: inherit
    # uses: ./.github/workflows/az_download.yml